### ISSUE TITLE
Beta function

### ISSUE THREAD

**Issue by dominik-kopczynski** [Amuwa/libAnova#3]
Hi,

Thank you for this tiny lovely library. However, after using it, I got different p-values in comparison to other libraries. After a look, I found that this particular line https://github.com/Amuwa/libAnova/blob/7bf9d0cc37139796882c149fd84ebb2aeafde5a5/anova/src/fdistribution.cpp#L135 might be incorrect. I guess you are computing here the inversed log-Beta function. Therefore you should use everywhere the log-gamma function (implemented in <math.h>). After changing to log-gamma, I immediately got the correct results.

Cheers,
Dominik

**Comment by Amuwa** [comment]
Hi Dominik,

Thanks for your feedback. 
I used to test against Matlab with some data and the results coincide.
Would you mind share any data that cause error?

Thanks with regards,
Amuwa

**Comment by dominik-kopczynski** [comment]
Sorry, my bad. Your code works because your gamma function actually computes the loggamma values. Please check:
gamma(10) = 362880
loggamma(10) = 12.801827
When I reimplemented your code in Python for test purposes, I got errors. Maybe you might rename your function to avoid confusion.

Cheers,
Dominik
